### ISSUE TITLE
add optional values get

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/config-cxx#10]

**Comment by eric-bodhi** [comment]
I'll do this one. I'll try to learn the project.

**Comment by eric-bodhi** [comment]
Could you however be a little more specific as what you want me to do?

**Comment by cieslarmichal** [comment]
Could you try to start with #9? It would be good for start, basically to throw error saying which field you are trying to read

**Comment by eric-bodhi** [comment]
> Could you try to start with #9? It would be good for start, basically to throw error saying which field you are trying to read

Sure
