### ISSUE TITLE
Add support for xml config 

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/config-cxx#18]

**Comment by PlungedInCode** [comment]
Assign it to me.
It would be great if you provide some info about this feature

**Comment by cieslarmichal** [comment]
Hey, xml parser needs to be added and load config into map, where key is flatten key like database.host. There was yaml support added couple days ago so you can reference it:
https://github.com/cieslarmichal/config-cxx/pull/24
Changes will be very similar except its xml not yaml :)
Also give a star to repo to make it more popular 💪
