### ISSUE TITLE
Fix macos clang++ workflow issue

### ISSUE THREAD

**Issue by AdamJovanovic** [cieslarmichal/config-cxx#36]
We'll most likely need to do the same thing as documented in this ticket: https://github.com/cieslarmichal/faker-cxx/issues/534

The apple clang workflow is still pointing to `macos-latest` in this repo so it'll break the next time someone creates a PR.

**Comment by cieslarmichal** [comment]
Yes, this ia the same as in faker 😅

**Comment by cieslarmichal** [comment]
done
