### ISSUE TITLE
should throw custom error saying which field user wants to get when env var is not set

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/config-cxx#9]

**Comment by eric-bodhi** [comment]
I'm confused, what ENV variable, the one in `ConfigProvider.cpp`?

**Comment by cieslarmichal** [comment]
lets say I have valid json config:

```
{
  "jwt": {
    "secret": null
  }
}
```

If I dont specify value here I am getting:

```
terminate called after throwing an instance of 'std::bad_any_cast'
  what():  bad any_cast
```

I would like to know on which config key it throwed an error (because I can have multiple fields in config and I dont know which one is wrong). It occurs type is provided (here nullptr needed to be cast to std::string).

I would be good to add try catch block and std::cerr log in Config.cpp file here: https://github.com/cieslarmichal/config-cxx/blob/140af2b50bd9c2e9c53e9a4a13af67ffbc88c4e7/src/Config.cpp#L43

**Comment by cieslarmichal** [comment]
I have app that uses config-cxx and you can see usage of configs here: https://github.com/momentum-devs/chatroom/tree/main/apps/server/config

**Comment by eric-bodhi** [comment]
I added these two lines:
```
std::cerr << "Error casting value for Config key '" << keyPath << "': " << e.what() << std::endl;
throw;
```

and got this result, is this what you were talking about?
![Screenshot from 2024-01-28 11-20-50](https://github.com/cieslarmichal/config-cxx/assets/101071809/1f3dc9d9-40af-4c15-b967-62299a855a52)

**Comment by eric-bodhi** [comment]
#11

**Comment by cieslarmichal** [comment]
It great but I would add more general message like Cannot resolve value for config key 'keypath' : e.what()
